development:
  adapter: <%=ENV['OPENSHIFT_DB_TYPE']%>
  encoding: utf8
  host: <%=ENV['OPENSHIFT_DB_HOST']%>
  port: <%=ENV['OPENSHIFT_DB_PORT']%>
  socket: <%=ENV['OPENSHIFT_DB_SOCKET']%>
  database: <%=ENV['OPENSHIFT_APP_NAME']%>
  username: <%=ENV['OPENSHIFT_DB_USERNAME']%>
  password: <%=ENV['OPENSHIFT_DB_PASSWORD']%>
  pool: 5

production:
  adapter: <%=ENV['OPENSHIFT_DB_TYPE']%>
  encoding: utf8
  host: <%=ENV['OPENSHIFT_DB_HOST']%>
  port: <%=ENV['OPENSHIFT_DB_PORT']%>
  socket: <%=ENV['OPENSHIFT_DB_SOCKET']%>
  database: <%=ENV['OPENSHIFT_APP_NAME']%>
  username: <%=ENV['OPENSHIFT_DB_USERNAME']%>
  password: <%=ENV['OPENSHIFT_DB_PASSWORD']%>
  pool: 5