development:
  adapter: mysql2
  encoding: utf8
  host: <%=ENV['OPENSHIFT_MYSQL_DB_HOST']%>
  port: <%=ENV['OPENSHIFT_MYSQL_DB_PORT']%>
  socket: <%=ENV['OPENSHIFT_MYSQL_DB_SOCKET']%>
  database: ivr
  username: <%=ENV['OPENSHIFT_MYSQL_DB_USERNAME']%>
  password: <%=ENV['OPENSHIFT_MYSQL_DB_PASSWORD']%>
  pool: 5

production:
  adapter: mysql2
  encoding: utf8
  host: <%=ENV['OPENSHIFT_MYSQL_DB_HOST']%>
  port: <%=ENV['OPENSHIFT_MYSQL_DB_PORT']%>
  socket: <%=ENV['OPENSHIFT_MYSQL_DB_SOCKET']%>
  database: ivr
  username: <%=ENV['OPENSHIFT_MYSQL_DB_USERNAME']%>
  password: <%=ENV['OPENSHIFT_MYSQL_DB_PASSWORD']%>
  pool: 5